<a href="https://colab.research.google.com/github/saiKelkar/Computer-Vision-Deep-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Arrays

In [2]:
# Create a rank 1 array
a = np.array([1, 2, 3])
print(type(a), a.shape, a[0], a[1], a[2])

# Change an element of the array
a[0] = 5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [3]:
# Create a rank 2 array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [5]:
# Create an array of all zeros
a = np.zeros((2, 2))
print(a)

[[0. 0.]
 [0. 0.]]


In [6]:
# Create an array of all ones
b = np.ones((1, 2))
print(b)

[[1. 1.]]


In [7]:
# Create a constant array
c = np.full((2, 2), 7)
print(c)

[[7 7]
 [7 7]]


In [8]:
# Create a 2x2 identity matrix
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [9]:
# Create an array filled with random values
e = np.random.random((2, 2))
print(e)

[[0.31402343 0.16311678]
 [0.37483926 0.71454576]]


Array math

In [14]:
x = np.array([[1, 2], [3, 4]], dtype = np.float64)
y = np.array([[5, 6], [7, 8]], dtype = np.float64)

# Element-wise sum <-- both produce array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [15]:
# Element-wise difference <-- both produce an array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [16]:
# Element-wise product <-- both produce an array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [17]:
# Element-wise division <-- both produce an array
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [18]:
# Element-wise square root <-- produces an array
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]
